Restructure HSI_Toolkit for packaging
GatorSense/hsi_toolkit_py pull request #4
Opened 2020-01-30 20:01 UTC by HaleySchuhl

Restructure the repo format to allow for a namespace package called hsi_toolkit. Added required files such as requirements, manifest, setup.py, and setup.cfg files. 

Removed parts of code that I found that is changing the path. 

[x] Tested compatibility with upload on PyPI
[x] Tested all functions imported by creating a new conda environment, installing hsi_toolkit, and then used the `help` function to check contents of all sub-packages (anomaly_detectors, classifiers, dim_reduction, endmember_extraction, signature_detectors, and util)

*Additional Context/Discussion* 
When we discussed packaging up these tools there was talk about only packaging up well tested tools. At the time of opening this PR, all functions that were available on the hsi_toolkit_py repo are imported with hsi_toolkit. However, Noah and I discussed how to efficiently update this once we receive a list of which functions are ready for primetime we can leave these functions where they are and move all beta-functions into a DEV sub-package that is not important with the package but this would still make this raw code available on this repo!

2020-04-14 18:21 UTC, HaleySchuhl commented
@susanmeerdink just wanted to confirm that `hsi_toolkit.signature_detectors.ftmf_detector` should go into the dev branch (also, is that a different name for the in progress sub-package that you all would prefer?). In your email you listed ftmf_statistic but I didn't see a function by this name. I came across one other question that comes down to your preference. Would you like all the dev functions sit within that sub-package or instead I could create folders inside the dev sub-package to mimic the tested python package structure. I can add these if you'd like!

2020-04-14 18:42 UTC, susanmeerdink commented
@HaleySchuhl Sorry for the typo! Yes I do mean hsi_toolkit.signature_detectors.ftmf_detector instead of ftmf_statistic. Please keep it as ftmf_detector instead of ftmf_statistic. I'm sorry but could you elaborate on or use examples of what my two options are for the in-progress functions? I'm not sure I understand what the two restructuring options are.

2020-04-14 18:57 UTC, HaleySchuhl commented
Option 1 (this is how the PR is currently): 
HSI_toolkit 
    anomaly_detectors sub-package
    classifiers sub-package
    dev sub-package
        ALL IN PROGRESS FUNCTION FILES
    dim_reduction 
    endmember_extraction
    signature_detectors
    util 

Option 2 : 
HSI_toolkit 
    anomaly_detectors sub-package
    classifiers sub-package
    dev sub-package
    anomaly_detectors sub-package
    classifiers sub-package
    dev sub-package
        folder of anomaly_detectors 
        folder of classifiers 
        folder of sub-package
        folder of anomaly_detectors 
        folder of classifiers sub-package
        folder of dim_reduction
        folder of dim_reduction 
        folder of endmember_extraction
        folder of signature_detectors
        folder of util 
    dim_reduction 
    endmember_extraction
    signature_detectors
    util

2020-04-14 19:40 UTC, susanmeerdink commented
@HaleySchuhl Thank you for the clarification. We would like to go with Option 1, but within the ALL IN PROGRESS folder have subfolders for each category (anomaly, classifiers, dim reduction, etc). Does that make sense?

2020-04-16 17:04 UTC, HaleySchuhl commented
I think this PR should be good to go once the conflicts are resolved! Just let me know if you have any comments/suggestions/questions! 😄

2020-04-22 15:47 UTC, nfahlgren requested changes
@HaleySchuhl I marked some PyCharm files that snuck in and updated the requirements.txt file a bit

2020-04-22 15:47 UTC, nfahlgren commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Some more PyCharm files snuck in.

2020-04-22 15:47 UTC, nfahlgren commented on .idea/hsi_toolkit_PR.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Some more PyCharm files snuck in.

2020-04-22 15:47 UTC, nfahlgren commented on .idea/markdown-navigator.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Some more PyCharm files snuck in.

2020-04-22 15:47 UTC, nfahlgren commented on .idea/markdown-navigator/profiles_settings.xml
> +<component name="MarkdownNavigator.ProfileManager">
Some more PyCharm files snuck in.

2020-04-22 15:47 UTC, nfahlgren commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Some more PyCharm files snuck in.

2020-04-22 15:47 UTC, nfahlgren commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Some more PyCharm files snuck in.

2020-04-22 15:47 UTC, nfahlgren commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Some more PyCharm files snuck in.

2020-04-22 15:47 UTC, nfahlgren commented on requirements.txt
> +sklearn
```suggestion
scikit-learn
pca
cvxopt
```

2020-05-29 18:33 UTC, nfahlgren commented
I would move all the demo scripts to a common demo folder in the main repo I think

2020-05-29 18:38 UTC, nfahlgren commented
@HaleySchuhl the file `hsi_toolkit/dev/endmember_extraction/__init__.py` should have:

```python
from hsi_toolkit.endmember_extraction.VCA import *
```

2020-05-29 18:42 UTC, nfahlgren commented
@HaleySchuhl I did some testing with SPICE and I think we just need to add `SPICE_HSI` to the `requirements.txt` file and in the file `hsi_toolkit/dev/endmember_extraction/__init__.py` we would add `import SPICE`

2020-06-12 19:37 UTC, closed without merging